### ISSUE TITLE
Unfortunately the protest-ware in the manifest means your package has been marked as critical

### ISSUE THREAD

**Issue by AndyDragon** [medikoo/es5-ext#141] opened 2022-04-01 20:26 UTC
I understand why you decided to add the protest-ware in the manifest, but that means your package is now flagged as critical malware and is blocking many systems.  One has to ask if this is the right place for such demonstration.

**Comment by medikoo** [comment] 2022-04-01 21:12
Duplicate of #116

**Closed by medikoo** 2022-04-01 21:12 UTC

**Comment by medikoo** [comment] 2022-04-01 21:14
Note, that there are no security implications made by the included manifest.

Please see https://snyk.io/blog/protestware-open-source-types-impact/ - it discusses specifically this package.
