### ISSUE TITLE
Add a .npmignore file for disk space saving

### ISSUE THREAD

**Issue by josephpage** [medikoo/es5-ext#37] opened 2015-08-06 10:14 UTC
Hello !

The `test` directory weights 1.7Mo. Is it possible to ignore it with .npmingore to save disk space ?

I can make a PR for this.
Thanks.

**Comment by medikoo** [comment] 2015-08-06 19:49
Closing as duplicate of #10 (see #11 for discussion on that matter)

**Closed by medikoo** 2015-08-06 19:49 UTC
